version: '3.7'

services:
    lnvisweb:
        image: maxkotlan/ln-visualizer-web:latest
        restart: on-failure
        stop_grace_period: 1m
        ports:
            - '5646:80'
        environment:
            LN_VISUALIZER_API_URL: 'http://lnvisapi:5647'
    lnvisapi:
        image: maxkotlan/ln-visualizer-api:latest
        restart: on-failure
        stop_grace_period: 1m
        volumes:
            - '/home/umbrel/umbrel/lnd:/lnd:ro'
        environment:
            LND_CERT_FILE: '/lnd/tls.cert'
            LND_MACAROON_FILE: '/lnd/data/chain/bitcoin/mainnet/readonly.macaroon'
            LND_SOCKET: 10.21.21.9:10009
networks:
   default:
      name: 'umbrel_main_network'
