version: "3.7"

services:
  web:
    image: ln-visualizer-web:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3078:80
  api:
    image: ln-visualizer-api:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 8080:8080