version: "3.7"

services:
  web:
    image: ln-visualizer-web:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3078:80
  api:
    image: ln-visualizer-api:latest
    environment:
      LND_CERT_FILE: "/lnd/tls.cert"
      LND_VIEW_MACAROON_FILE: "/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/readonly.macaroon"
      LND_ADDRESS: https://$LND_IP:$LND_GRPC_PORT