name: LnVisualizerWebBuild

on:
    push:
        branches: [main]
        tags:
            - v*.*.*

jobs:
    build-web:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: './Dockerfile-web'
                  push: true
                  tags: maxkotlan/ln-visualizer-web:latest,maxkotlan/ln-visualizer-web:${{ env.RELEASE_VERSION }}
    build-api:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: './Dockerfile-api'
                  push: true
                  tags: maxkotlan/ln-visualizer-api:latest,maxkotlan/ln-visualizer-web:${{ env.RELEASE_VERSION }}
