name: LnVisualizerWebBuild

on:
    push:
        branches: [main]
        tags:
            - v*.*.*

jobs:
    build-web:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
              with:
                  image: tonistiigi/binfmt:latest
                  platforms: arm64,arm

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push release
              if: env.RELEASE_VERSION != 'main'
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: './Dockerfile-web'
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  push: true
                  tags: maxkotlan/ln-visualizer-web:${{ env.RELEASE_VERSION }}

            - name: Build and push latest
              if: env.RELEASE_VERSION == 'main'
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: './Dockerfile-web'
                  push: true
                  tags: maxkotlan/ln-visualizer-web:latest
    build-api:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
              with:
                  image: tonistiigi/binfmt:latest
                  platforms: arm64,arm

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push release
              if: env.RELEASE_VERSION != 'main'
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: './Dockerfile-api'
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  push: true
                  tags: maxkotlan/ln-visualizer-api:${{ env.RELEASE_VERSION }}

            - name: Build and push latest
              if: env.RELEASE_VERSION == 'main'
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: './Dockerfile-api'
                  push: true
                  tags: maxkotlan/ln-visualizer-api:latest
