name: LnVisualizerWebBuild

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker build --tag maxkotlan/ln-visualizer-web:$(date +%s) -f Dockerfile-web .
